### ISSUE TITLE
'Unexpected newline in header key'

### ISSUE THREAD

**Issue by vandenoever** [staktrace/mailparse#7] opened 2016-12-03 16:03 UTC
A newline error is reported in a real-world email file.

Here is the relevant fragment:

[newline.txt](https://github.com/staktrace/mailparse/files/628941/newline.txt)

**Comment by staktrace** [comment] 2016-12-04 07:47
Thanks for reporting this! I landed a commit that should fix this. I put your testcase in as a regression test as well. I'll push out a 0.5.0 version shortly which includes this fix and the other changes you submitted.

**Closed by staktrace** 2016-12-04 07:47 UTC

**Comment by staktrace** [comment] 2016-12-04 07:49
Sorry, make that 0.4.1, since the changes are just bugfixes.

**Comment by vandenoever** [comment] 2016-12-04 08:59
Very nice since I did not progress very far on fixing it. Reading your fix helps me understand the code.
